/*
 * generated by Xtext 2.20.0
 */
package it.unica.co2.diogenes.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
class DiogenesProposalProvider extends AbstractDiogenesProposalProvider {
}
