/*
 * generated by Xtext 2.21.0.M3
 */
package it.unica.co2.diogenes.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class DiogenesProposalProvider extends AbstractDiogenesProposalProvider {
}
