os: linux
dist: xenial
language: java
jdk:
- openjdk8
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - CO2_HONESTY_CHECKER_VERSION=5.2.0
  - LATEST_VERSION=$(git log -n 1 --pretty=format:"%h")
before_script:
- "./scripts/install-deps.sh"
script:
- mvn -f it.unica.co2.diogenes.parent/ -U clean install
notifications:
  email:
    recipients:
    - atzeinicola@gmail.com
    on_success: change
    on_failure: always


deploy:
  provider: releases
  token:
    secure: "CAMskFZ1wv7Y3qWM01ZWMAY4eaMD+fC37WztGdAiz8eFuzITxhVNltd70zMGS+o0nGZt6HD+gsk1uSuVU94+N+4Dly/I0G4Zr4PctjZQZBfPyonnOAivpZzGKCvne0Fw1AkZRhkRP4qOqp1NJEu82OdwlUhDoujrcZbBCO1RcJBvFw27qjuKoLKDB00i80B03S09gHX3cqi5Z4GJzMaFN/7Mf/RHQFDw54F8Gam2UcxbKHWWYd7HlbItBMNAw1rhQqpSr5iEfcgjmkRBBBx8l9Pz8A1/Z/78YywmELzKUYB8kR8WSgxO/DGcuhRS5Nz9gQ4WqLYvMPCTlNNiNrHIX6lyQeBgfqlWjvLjGaPp7VbIFTuaEErcnvc1VUpkaifPfI55kTdVQpDT8qton5IosccQydVwk6Eteho0iGWFLIDawllBqlsmZ+D5ZFJC4BFFxCHNpZ76x3klFRD7fFHXehZKInrq/qS8e4jAjNqv+GDXwwyNb81H3jvPNuw44Zw85FU6O6JQn55ulhjH+97JzZtmpl/fAGzYV2DDF1ZWYMoiSzukr1fksMcL0z3nTiI7pZe1fG5IE96f5yZrz4mtjgnObcT3ImEa+yFHF5F7Wbx5j1O8uF4s3wUa8U0Hnrzj13fFi2wzUqKqrbJw1+GEYGlQmBlesbXvIxJ8CGyzTrg="
  file_glob: true
  file: it.unica.co2.diogenes.parent/it.unica.co2.diogenes.repository/target/it.unica.co2.diogenes.repository-*.zip
  on:
    tags: true
    repo: diogenes-lang/diogenes
  skip_cleanup: true
