language: java
jdk:
- openjdk8

services:
- docker

cache:
  directories:
  - "$HOME/.m2"

env:
  global:
  - CO2_HONESTY_CHECKER_VERSION=5.2.0
  - LATEST_VERSION=$(git log -n 1 --pretty=format:"%h")

before_script:
- "./scripts/install-deps.sh"

script:
- mvn -f it.unica.co2.diogenes.parent/ -U clean install

notifications:
  email:
    recipients:
    - atzeinicola@gmail.com
    on_success: change
    on_failure: always
