/*
 * generated by Xtext 2.20.0
 */
package it.unica.co2.diogenes.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class DiogenesWebModule extends AbstractDiogenesWebModule {
}
