/*
 * generated by Xtext 2.21.0.M3
 */
package it.unica.co2.diogenes.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import it.unica.co2.diogenes.DiogenesRuntimeModule;
import it.unica.co2.diogenes.DiogenesStandaloneSetup;
import it.unica.co2.diogenes.ide.DiogenesIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class DiogenesWebSetup extends DiogenesStandaloneSetup {
	
	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new DiogenesRuntimeModule(), new DiogenesIdeModule(), new DiogenesWebModule()));
	}
	
}
