/*
 * generated by Xtext 2.21.0.M3
 */
package it.unica.co2.diogenes.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class DiogenesWebModule extends AbstractDiogenesWebModule {
}
