/*
 * generated by Xtext
 */
package it.unica.co2;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class CO2StandaloneSetup extends CO2StandaloneSetupGenerated{

	public static void doSetup() {
		new CO2StandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

