/*
 * generated by Xtext
 */
package it.unica.co2;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ContractsRuntimeModule extends it.unica.co2.AbstractContractsRuntimeModule {

}
