/*
 * generated by Xtext
 */
package it.unica.co2;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ContractsStandaloneSetupOld extends ContractsStandaloneSetupGenerated{

	public static void doSetup() {
		new ContractsStandaloneSetupOld().createInjectorAndDoEMFRegistration();
	}
}

