/*
 * generated by Xtext 2.21.0.M3
 */
package it.unica.co2.diogenes.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import it.unica.co2.diogenes.DiogenesRuntimeModule;
import it.unica.co2.diogenes.DiogenesStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class DiogenesIdeSetup extends DiogenesStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new DiogenesRuntimeModule(), new DiogenesIdeModule()));
	}
	
}
