/*
 * generated by Xtext
 */
package it.unica.co2.validation

import it.unica.co2.co2.Co2Package
import it.unica.co2.co2.EmptyProcess
import it.unica.co2.co2.ProcessDefinition
import it.unica.co2.xsemantics.validation.CO2TypeSystemValidator
import org.eclipse.xtext.EcoreUtil2
import org.eclipse.xtext.validation.Check
import it.unica.co2.co2.HonestyDeclaration

/**
 * This class contains custom validation rules. 
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class CO2Validator extends CO2TypeSystemValidator {

	@Check
	def void checkContractNameIsUnique(ProcessDefinition procDef) {
		var root = EcoreUtil2.getRootContainer(procDef);
		for (other: EcoreUtil2.getAllContentsOfType(root, ProcessDefinition)){
			
			if (procDef!=other && procDef.getName.equals(other.name)) {
				error("Process names have to be unique", 
					Co2Package.Literals.PROCESS_DEFINITION__NAME
				);
				return;
			}
		}
	}

	@Check
	def void checkHonestyDeclaration(HonestyDeclaration honestyDecl) {
		/*
		 * each process must appear once and declared without params
		 */
		for (var i=0; i<honestyDecl.processes.size; i++) {
			var p = honestyDecl.processes.get(i)
			if (p.params.size > 0) {
				error("You can check only processes without args", 
					Co2Package.Literals.HONESTY_DECLARATION__PROCESSES,
					i
				);
			}
		}
		
		for (var i=0; i<honestyDecl.processes.size-1; i++) {
			
			for (var j=i+1; j<honestyDecl.processes.size; j++) {
				var p1 = honestyDecl.processes.get(i)
				var p2 = honestyDecl.processes.get(j)
				if (p1.name == p2.name) {
					error("Process already present", 
						Co2Package.Literals.HONESTY_DECLARATION__PROCESSES,
						j
					);
				}
			}
		}
			
	}

	@Check
	def void checkEmptyProcess(EmptyProcess empty) {
		info("Empty process can be omitted", 
			Co2Package.Literals.EMPTY_PROCESS__VALUE
		);
	}
	
}
