/*
 * generated by Xtext
 */
package it.unica.co2.ui.contentassist

import it.unica.co2.ui.contentassist.AbstractContractsProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class ContractsProposalProvider extends AbstractContractsProposalProvider {
}
