/*
 * generated by Xtext 2.21.0.M3
 */
package it.unica.co2.diogenes.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class DiogenesUiModule extends AbstractDiogenesUiModule {

	public DiogenesUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
