/*
 * generated by Xtext 2.20.0
 */
package it.unica.co2.diogenes.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class DiogenesUiModule extends AbstractDiogenesUiModule {
}
