/*
 * generated by Xtext
 */
package it.unica.co2.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CO2UiModule extends it.unica.co2.ui.AbstractCO2UiModule {
	public CO2UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
