/*
 * generated by Xtext
 */
package it.unica.co2.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ContractsUiModule extends it.unica.co2.ui.AbstractContractsUiModule {
	public ContractsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
