/*
 * generated by Xtext 2.21.0.M3
 */
package it.unica.co2.diogenes;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DiogenesRuntimeModule extends AbstractDiogenesRuntimeModule {
}
