/*
 * generated by Xtext 2.20.0
 */
package it.unica.co2.diogenes


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DiogenesStandaloneSetup extends DiogenesStandaloneSetupGenerated {

    def static void doSetup() {
        new DiogenesStandaloneSetup().createInjectorAndDoEMFRegistration()
    }
}
