/*
 * generated by Xtext 2.20.0
 */
package it.unica.co2.diogenes


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class DiogenesRuntimeModule extends AbstractDiogenesRuntimeModule {
}
